=== nieti723/LenguajeMarcas/xml/boletin2/ejercicio4/ejercicio4.dtd
<!ELEMENT equipos (equipo+)>

<!ELEMENT equipo (nombre, nacionalidad, presupuesto?, (normal | doble), sweepers, pista, fechaFundacion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT presupuesto (#PCDATA)>
<!ELEMENT normal EMPTY>
<!ELEMENT doble EMPTY>

<!ELEMENT sweepers (sweeper+)>
<!ELEMENT sweeper (nombre, apellidos, edad, sexo)>
<!ATTLIST sweeper dni CDATA #REQUIRED>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>

<!ELEMENT pista (nombre, asientos, direccion)>
<!ELEMENT asientos (#PCDATA)>
<!ELEMENT direccion (calle, numero, poblacion)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT poblacion (cp?, provincia)>
<!ATTLIST poblacion valor CDATA #REQUIRED>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>

<!ELEMENT fechaFundacion (dia, mes, anyo)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>

=== nieti723/LenguajeMarcas/xml/boletin2/ejercicio4/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos SYSTEM "ejercicio4.dtd">
<equipos>
    <equipo>
        <nombre>El betis</nombre>
        <nacionalidad>Espa√±a</nacionalidad>
        <presupuesto/>
        <normal/>
        <sweepers>
            <sweeper dni = "53962293S">
                <nombre>Juan</nombre>
                <apellidos>Nieto Acosta</apellidos>
                <edad>20</edad>
                <sexo>Masculino</sexo>
            </sweeper>
        </sweepers>
        <pista>
            <nombre>Bernabeu</nombre>
            <asientos>23</asientos>
            <direccion>
                <calle>Fray Cipriano de Utrera</calle>
                <numero>9</numero>
                <poblacion valor = "Utrera">
                    <cp>41710</cp>
                    <provincia>Sevilla</provincia>
                </poblacion>
            </direccion>
        </pista>
        <fechaFundacion>
            <dia>22</dia>
            <mes>12</mes>
            <anyo>2004</anyo>
        </fechaFundacion>
    </equipo>
</equipos>
